version = 1

[build]
  image = "python:3.9-slim"

[[services]]
  name = "app"
  image = "python:3.9-slim"
  port = 5000
  command = "bash -c 'apt-get update && apt-get install -y python3 && pip install -r requirements.txt && python app.py'"
